# Generated by Django 2.1.1 on 2020-12-24 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
